mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    
]



from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('nstpapp.urls')),
    
    
    # path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'))
]

mysite/nstpapp/urls.py
from django.urls import path
from . import views
from django.conf.urls import static
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from django.urls import include, re_path

# password reset
from django.contrib.auth import views as auth_views

from django.urls import reverse_lazy

app_name = 'activities'

urlpatterns = [
    path('', views.index, name='index'),
    path('navbar/', views.navbar, name='navbar'),
    path('admin_nav/', views.admin_nav, name='admin_nav'),
    path('logout_student/', views.logout_student, name='logout_student'),
    path('signup_page/', views.signup_page, name='signup_page'),
    path('signup/', views.signup, name='signup'),
    path('login_page/',views.login_page, name='login_page'),
    path('signin/', views.signin, name='signin'),
    path('dashboard_page/', views.dashboard_page, name='dashboard_page'),
    path('profile_page/', views.profile_page, name='profile_page'),
    path('editprofile/', views.editprofile, name='editprofile'),
    path('edit/<str:id>', views.edit, name='edit'),
    path('others/', views.others, name='others'),
    path('edit_others/<str:id>', views.edit_others, name='edit_others'),
    # path('health/', views.health, name='health'),
    path('edit_health/', views.edit_health, name='edit_health'),
    path('file_manager/', views.file_manager, name='file_manager'),
    path('files_rotc/', views.files_rotc, name='files_rotc'),
    path('rotc_files/', views.rotc_files, name='rotc_files'),
    path('files_cwts/', views.files_cwts, name='files_cwts'),
    path('cwts_files/', views.cwts_files, name='cwts_files'),
    path('fields/', views.fields, name='fields'),
    path('field_rotc/', views.field_rotc, name='field_rotc'),
    
    
    
    # admin urls
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin_staff/', views.admin_staff, name='admin_staff'),
    path('admin_pending/', views.admin_pending, name='admin_pending'),
    path('admin_view_profile/<str:id>', views.admin_view_profile, name='admin_view_profile'),
    path('cwts_admin_view_profile/<str:id>', views.cwts_admin_view_profile, name='cwts_admin_view_profile'),

    path('approve/<str:idnumber>', views.approve, name='approve'),
    path('cw_approve/<str:idnumber>', views.cw_approve, name= 'cw_approve'),
    path('decline/<str:id>', views.decline, name='decline'),
    path('cw_decline/<str:id>', views.cw_decline, name='cw_decline'),

    path('admin_rejected/', views.admin_rejected, name='admin_rejected,'),
    path('custom/', views.custom, name='custom'),
    path('rejected_email_page/<str:id>', views.rejected_email_page, name='rejected_email_page'),
    path('school_years/', views.school_years, name='school_years'),
    path('create_sy/', views.create_sy, name='create_sy'),
    # path('allumni_page/', views.allumni_page, name='allumni_page'),
    path('allumni_content/', views.allumni_content, name='allumni_content'),
    path('delete_sy/<str:years>', views.delete_sy, name='delete_sy'),
    path('create_platoon_page/', views.create_platoon_page, name='create_platoon_page'),
    path('create_section/', views.create_section, name='create_section'),
    path('counts/', views.counts, name='counts'),
    path('pl_content/', views.pl_content, name='pl_content'),
    path('section_content/', views.section_content, name='section_content'),
    path('view_images/<str:id>', views.view_images, name='view_images'),
    path('create_platoon_page2/', views.create_platoon_page2, name='create_platoon_page2'),
    path('manage_section/', views.manage_section, name='manage_section'),
    path('edit_manage/<str:id>', views.edit_manage, name='edit_manage'),
    path('export/', views.export, name='export'),
    path('edit_student/<str:id>', views.edit_student, name='edit_student'),
    path('attendance_page/', views.attendance_page, name='attendance_page'),
    path('create_day/',views.create_day, name='create_day'),
    path('create_annoucement/', views.create_announcement, name='create_announcement'),
    path('edit_announcement/<str:id>', views.edit_announcement, name='edit_announcement'),
    path('delete_announcement/<str:id>', views.delete_announcement, name='delete_announcement'),
    path('attendance_sections/', views.attendance_sections, name='attendance_sections'),
    path('attendance_main/', views.attendance_main, name='attendance_main'),
    path('attendance_main_page/', views.attendance_main_page, name='attendance_main_page'),
    # path('record/<str:id>', views.record, name='record'),
    path('update_attendance/', views.update_attendance, name='update_attendance'),
    path('add_students/', views.add_students, name='add_students'),
    path('assign_section/', views.assign_section, name='assign_section'),
    path('update_sy/', views.update_sy, name='update_sy'),
    path('update_officially/<str:id>', views.update_officially, name='update_officially'),
    path('cert_page/', views.cert_page, name='cert_page'),
    path('generate/', views.generate, name='generate'),
    path('open_cert_page/', views.open_cert_page, name='open_cert_page'),
    path('add_details/', views.add_details, name='add_details'),
    path('update_acts/', views.update_acts, name='update_acts'),
    path('r_approve/<str:idnumber>', views.r_approve, name='r_approve'),
    path('r_decline/<str:id>', views.r_decline, name='r_decline'),
    path('c_approve/<str:idnumber>', views.c_approve, name='c_approve'),
    path('c_decline/<str:id>', views.c_decline, name='c_decline'),


    path('download/', views.download, name='download'),
    path('download1/', views.download1, name='download1'),
    path('update_manage/', views.update_manage, name='update_manage'),
    path('admin_files/', views.admin_files, name='admin_files'),
    path('open_folder/<str:section_created>', views.open_folder, name='open_folder'),
    path('dropped/', views.dropped, name='dropped'),
    path('download3/', views.download3, name='download3'),
  
    path('download4/', views.download4, name='download4'),
    path('sample_attendance/', views.sample_attendance, name='sample_attendance'),
    path('create_td/', views.create_td, name='create_td'),
    path('open_date/', views.open_date, name='open_date'),
    path('open_sections/', views.open_sections, name='open_sections'),
    path('all_sections/', views.all_sections, name='all_sections'),
    path('del_tday/<str:id>', views.del_tday, name='del_tday'),
    path('download5/', views.download5, name='download5'),
    path('rec_attendance/', views.rec_attendance, name='rec_attendance'),
    path('show_students/', views.show_students, name='show_students'),
    path('update_sys/', views.update_sys, name='update_sys'),
    path('update_att_credits/', views.update_att_credits, name='update_att_credits'),
    path('grades/', views.grades, name='grades'),
    path('modify_grades/', views.modify_grades, name='modify_grades'),
    path('set_activities/', views.set_activities, name='set_activities'),
    path('save_grade/', views.save_grade, name='save_grade'),
    path('edit_activities/<str:id>', views.edit_activities, name='edit_activities'),
    path('delete_activities/<str:id>', views.delete_activities, name='delete_activities'),
    path('attendance_tab/', views.attendance_tab, name='attendance_tab'),
    path('create_td2/', views.create_td2, name='create_td2'),
    path('delete_td/<str:id>', views.delete_td, name='delete_td'),
    path('midterms/', views.midterms, name='midterms'),
    path('add_midterm/', views.add_midterm, name='add_midterm'),
    path('modify_midterm/', views.modify_midterm, name='modify_midterm'),
    # path('save_grade_2/', views.save_grade_2, name='save_grade_2'),
    path('save_midterm/', views.save_midterm, name='save_midterm'),
    path('finals_/', views.finals_, name='finals_'),
    path('modify_finals/', views.modify_finals, name='modify_finals'),
    path('add_finals/', views.add_finals, name='add_finals'),
    path('delete_midterm/<str:id>', views.delete_midterm, name='delete_midterm'),
    path('delete_finals/<str:id>', views.delete_finals, name='delete_finals'),
    path('save_finals/', views.save_finals, name='save_finals'),
    path('final_grade/', views.final_grade, name='final_grade'),
    path('access_final_grade/', views.access_final_grade, name='access_final_grade'),
    path('save_finale_grades/', views.save_finale_grades, name='save_finale_grades'),
    path('merits/', views.merits, name='merits'),
    path('access_merits/', views.access_merits, name='access_merits'),
    path('save_merits/', views.save_merits, name='save_merits'),
    path('approve2/<str:id>', views.approve2, name='approve2'),
    path('decline2/<str:id>', views.decline2,name='decline2'),
    path('custom36/', views.custom36, name='custom36'),
    path('open_csv/', views.open_csv, name='open_csv'),
    path('open_wala/', views.open_wala, name='open_wala'),
    path('read_attendance/', views.read_attendance, name='read_attendance'),
    path('before_csv/', views.before_csv, name='before_csv'),
    path('update_section/', views.update_section, name='update_section'),
    path('cwts_attendance/', views.cwts_attendance, name='cwts_attendance'),
    path('cwts_td/', views.cwts_td, name='cwts_td'),
    path('open_cwts_date/', views.open_cwts_date, name='open_cwts_date'),
    path('display_csv/', views.display_csv, name='display_csv'),
    path('open_cwts_csv/', views.open_cwts_csv, name='open_cwts_csv'),
    path('save_cwts_attendance/', views.save_cwts_attendance, name='save_cwts_attendance'),
    path('del_cwts_tday/<str:id>', views.del_cwts_tday, name='del_cwts_tday'),
    path('cwts_attendance_tab/', views.cwts_attendance_tab, name='cwts_attendance_tab'),
    path('cwts_show_students/', views.cwts_show_students, name='cwts_show_students'),
    path('cwts_course_evaluation/', views.cwts_course_evaluation, name='cwts_course_evaluation'),

mysite/nstpapp/templates/activities/attendance_section.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="icon" href="../../static/images/tup.png">
    <link rel="stylesheet" href="../../static/admin_css/attendance_section.css">
    <link rel="stylesheet" href="../../static/admin_css/admin_nav.css">
</head>

<body>
    {{ redirect_to_login_immediately }} {% include 'activities/admin_nav.html' %}

    <section class="home-section">
        <div class="heads">
            <a href="/attendance_page">
                <h1 class="text"><i class='bx bxs-dashboard' style="vertical-align: middle;"></i> Manage Attendance &nbsp;|</h1>
            </a>

            <h1 class="text"><i class='bx bxs-dashboard'></i> Sections
            </h1>
        </div>
        <div class="bg">
            <div class="overall">
                <div class="left">
                    <h1 style="font-size: 20px;">All Sections {{s.title}}</h1>
                    <p1 style="color:green; font-size:15px; font-weight:bold;"><i class='bx bxs-grid' style="vertical-align:middle; font-size: 20px; color:green; font-weight:bolder;"></i> {{section1}} Sections</p1>
                    <br>&nbsp;<br>
                    <div class="row">
                        {% for s in platoons %}
                        <form action="{% url 'activities:attendance_main'  %}" class="column" style="text-decoration: none;" method="POST">
                            {% csrf_token %}
                            <div class="card">
                                <p>{{s.section_created}}</p><br>


                                <input type="hidden" value="{{s.section_created}}" name="getSection">

                                <button type="submit" class="btn btn-info">Take Attendance</button>
                            </div>
                        </form>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </section>

</body>

</html>

mysite/nstpapp/templates/activities/cwts_rejected.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>admin rejected students</title>

    <!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script> -->
    <link rel="stylesheet" href="../../static/admin_css/admin_rejected.css">
    <link rel="stylesheet" href="../../static/admin_css/admin_nav.css">
    <!-- icon for seacrch -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/solid.css">

    <!-- for table pagination -->
    <link rel="stylesheet" href="../../static/admin_css/minmin.css">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous"> -->

</head>

<body>
    {% include 'activities/admin_nav.html' %}
    <section class="page-content">
        <div class="heads">
            <h1 class="text"><i class='bx bx-time'></i>CWTS DECLINED</h1><br>
        </div>
        <div class="bg">
            <!-- <ul class="nav nav-tabs nav-pills nav-fill">
                <li class="nav-item">
                    <a href="/school_years" class="nav-link">School Year</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/admin_staff">Officially Enrolled <i class='bx bxs-badge-check' style="vertical-align: middle;"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin_pending">Pending Enrollees <i class='bx bxs-time-five' style="vertical-align: middle;" ></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" style="background-color: red;" href="/admin_rejected">Rejected <i class='bx bxs-user-minus' style="vertical-align: middle;"></i></a>
                </li>


            </ul> -->
            <!-- modal -->
            <br>

            <div>
                <div class="table-responsive">
                    <p1 style="font-size:20px;color:#000000;">List of all Declined ROTC Student/s.</p1><br>&nbsp;<br>
                    <table id="table1" class="table table-bordered table-hover ">
                        <thead class="thead">
                            <tr>
                                <th scope="col">ID NUMBER</th>
                                <th scope="col">FULL NAME</th>
                                <th scope="col">COURSE</th>
                                <th scope="col">DATE REGISTERED</th>
                                <th scope="col">DECLINING REASON</th>
                                <th scope="col">DATE DECLINED</th>
                                <th scope="col">DECLINED BY</th>
                                <th scope="col" style="text-align: center;">VIEW PROFILE</th>
                                <!-- <th scope="col" style="text-align: center;">Action</th> -->

                            </tr>
                        </thead>
                        <tbody>
                            {% for s in rejected %} {% if s.idnumber %}
                            <tr>


                                <td>
                                    {{s.idnumber}}
                                </td>
                                <td>{{s.firstname}} {{s.middlename}} {{s.lastname}}</td>
                                <td>{{s.section}}</td>
                                <td style="color: #009113;">{{s.date_joined}}</td>
                                <td style="color: #ff0000;">{{s.note}}</td>
                                <td>{{s.date_declined}}</td>
                                <td>{{s.approved_by}}</td>

                                <td class="tar">
                                    <a href="{% url 'activities:rejected_cwts_profile' s.id %}" target="_self" title="View student profile"><i class="fa-solid fa-eye"></i>
                                         View Profile
                                    </a>
                                </td>


                                <!-- <td class="actions">
                                    <div class="ehe">
                                        <form action="{% url 'activities:c_approve' s.idnumber %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="getID" value="{{s.idnumber}}"><button type="submit" class="btn btn-success"><i class='bx bx-check'></i>  Approve</button>
                                        </form>
                                    </div><br>&nbsp;<br>
                                    <div class="ehe">
                                        <a href="{% url 'activities:c_decline' s.id %}" class="btn btn-danger"> Remove</a>
                                    </div>


                                </td> -->

                            </tr>
                            {% endif %} {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>







        </div>


    </section>





    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>


    <!-- pagination -->
    <script src="../../static/js/pag.js"></script>
    <script src="../../static/js/datbot.js"></script>
    <script src="../../static/js/dat.js"></script>
    <script>
        $(document).ready(function() {
            $('#table1').DataTable({
                pagingType: 'full_numbers',
            });
        });
    </script>


    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- <script>

        {% for msg1 in messages %}
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '{{msg1}}',
            showConfirmButton: false,
            timer: 2500
          }) {% endfor %}
    </script>   -->

    <script>
        $('.btn-danger').on('click', function(e) {
            e.preventDefault();
            var self = $(this);
            console.log(self.data('title'))

            Swal.fire({
                title: 'Are you sure?',
                text: "This will be permanently remove from your records",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',

                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                    location.href = self.attr('href')
                }
            })
        })
    </script>
</body>

</html>

mysite/nstpapp/templates/activities/file_manager.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>file manager</title>
    <link rel="stylesheet" href="../../static/css/file_manager.css">
</head>

<body>
    {% include 'activities/navbar.html' %}

    <section class="home-section">
        <div class="lines">
            <a href="/file_manager">
                <h1 class="text"><i class='bx bx-folder'></i> File Manager</h1>
            </a>
        </div>
        <div class="bg">
            <div class="conts">
                <div class="first">
                    <div class="cards">
                        <div class="head">
                            <h1 class="tit" style="text-decoration: none;">ROTC</h1><br>
                            <img src="../../static/images/file.png" class="icons">

                        </div>
                        <div class="botm">
                            <a href="/rotc_files" class="open">Open</a>

                        </div>

                    </div>


                    <div class="cards">
                        <div class="head">
                            <h1 class="tit">CWTS</h1><br>
                            <img src="../../static/images/file.png" class="icons">


                        </div>
                        <div class="botm">
                            <a href="/cwts_files" class="open">Open</a>

                        </div>
                    </div>


                </div>

            </div>



        </div>







    </section>


    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        {%for m in messages %}
            Swal.fire({
                icon: '',
                text: '{{ m }}'
            })
        {% endfor %}
    </script>

</body>

</html>

mysite/nstpapp/templates/activities/rejected_email.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>admin rejected students</title>

    <!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script> -->
    <link rel="stylesheet" href="../../static/admin_css/admin_rejected.css">
    <link rel="stylesheet" href="../../static/admin_css/admin_nav.css">
    <!-- icon for seacrch -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/solid.css">

    <!-- for table pagination -->


</head>

<body>
    {% include 'activities/admin_nav.html' %}
    <section class="home-section">
        <div class="heads">
            <h1 class="text"><i class='bx bx-user-minus' style="vertical-align: middle;"></i> REJECTED</h1><br>
        </div>
        <div class="bg">
            <ul class="nav nav-tabs nav-pills nav-fill">
                <li class="nav-item">
                    <a href="/school_years" class="nav-link">School Year</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/admin_staff">Officially Enrolled <i class='bx bxs-badge-check' style="vertical-align: middle;"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin_pending">Pending Enrollees <i class='bx bxs-time-five' style="vertical-align: middle;" ></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" style="background-color: red;" href="/admin_rejected">Rejected <i class='bx bxs-user-minus' style="vertical-align: middle;"></i></a>
                </li>


            </ul>
            <!-- modal -->

            <div class="inside">
                <div class="table-responsive">
                    <p1 style="font-size:14px;color:#000000;">List of all Rejected Student/s.</p1><br>
                    <table id="table1" class="table table-bordered table-hover ">
                        <thead class="thead">
                            <tr>
                                <th scope="col">ID NUMBER</th>
                                <th scope="col">FULL NAME</th>
                                <th scope="col">EMAIL</th>

                                <th scope="col">COURSE</th>
                                <th scope="col">FIELD</th>
                                <th scope="col">VIEW PROFILE</th>
                                <th scope="col">SEND EMAIL</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for s in rejects %} {% if s.idnumber %}
                            <tr>

                                <td>
                                    {{s.idnumber}}
                                </td>
                                <td>{{s.firstname}} {{s.middlename}} {{s.lastname}}</td>
                                <td>{{s.email}}</td>

                                <td>{{s.section}}</td>
                                <td>{{s.field}}</td>
                                <td>
                                    <a href="{% url 'activities:rejected_email_page' s.id %}" target="_self" title="Click to compose custom Email"><i class='bx bxs-show' style="vertical-align: middle;"></i>
                                        View Profile</a>
                                </td>
                                <td>
                                    <a href="{% url 'activities:rejected_email_page' s.id %}" target="_self" title="Click to compose custom Email">
                                        <button type="button" class="btn btn-info"> <i class='bx bx-envelope' style="vertical-align: middle;"></i> Send Email</button>
                                    </a>
                                </td>

                                <td class="actions">
                                    <div class="ehe">
                                        <form action="{% url 'activities:r_approve' s.idnumber %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="getID" value="{{s.idnumber}}"><button type="submit" class="btn btn-success"><i class='bx bx-check'></i>  Approve</button>
                                        </form>
                                    </div><br>&nbsp;<br>
                                    <div class="ehe">
                                        <form action="{% url 'activities:r_decline' s.id %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="getID2" value="{{s.idnumber}}"><button type="submit" class="btn btn-danger"><i class='bx bx-x-circle'></i> Remove</button>
                                        </form>
                                    </div>


                                </td>

                            </tr>
                            {% endif %} {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>







        </div>


    </section>

    <div>{% for k in ems %}
        <form action="{% url 'activities:custom'%}" method="post">
            {% csrf_token %}
            <div class="modal fade" id="exampleModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Compose Email</h5>


                        </div>
                        <div class="modal-body">
                            <form>
                                <div class="form-group">
                                    <label for="recipient-name" class="col-form-label">Recipient:</label>
                                    <input type="email" name="cusemail" value="{{k.email}}" required id="rec" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="recipient-name" class="col-form-label">Subject:</label>
                                    <input type="text" name="emailtext" placeholder="SUBJECT" required id="sub" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Message:</label>
                                    <textarea class="form-control" id="message-text" name="message" required placeholder="Type Your Message Here"></textarea>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <a href="/admin_rejected"><button type="button" class="btn btn-secondary" >Close</button></a>
                            <button type="submit" class="btn btn-primary">Send message</button>
                        </div>
                    </div>
                </div>
            </div>


        </form>
        {% endfor %}
    </div>





    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>


    <script type="text/javascript">
        $(document).ready(function() {
            $("#exampleModal").modal('show');
        });
    </script>
    <!-- pagination -->

</body>

</html>